name: Deploy Cloud Function

# triggers for our workflow
on:
  # opening a pull request to main branch will be a trigger
  pull_request:
    branches: ["main"]
  # any code pushed to main branch will also be a trigger
  push:
    branches: ["main"]

env:
  X_RapidAPI_Key: ${{ secrets.X_RapidAPI_Key }}
  X_RapidAPI_Host: ${{ secrets.X_RapidAPI_Host }}

# jobs definition
jobs:
  health-check-job: # health check job for testing and code formatting check
    runs-on: ubuntu-latest # os for running the job
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.8] # for multiple python version

    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
      - name: Cache dependency # caching dependency will make our build faster.
        uses: actions/cache@v2 # for more info checkout pip section documentation at https://github.com/actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python ${{ matrix.python-version }} # setting python environment to 3.x
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies # install application requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-flake8.txt
      - name: Check Syntax
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: flake8 --all-files
      - name: Run Coverage Test # running tests
        run: |
          pip install coverage
          coverage run --source=. -m unittest discover
          coverage report -m